# -*- coding: utf-8 -*-
"""Credit_Risk_MLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCFETvIdcKElxOxTeWA3HYr6wshoYnou

#GAURAV KUMAR
#2501940033
#Deep Learning Architectures and Techniques (ETMMDL274)
---------------------------------------------------------------------------------------------
# **ASSIGNMENT - 1**
##**Neural Network–Based Credit Risk Prediction Using a Multi-Layer Perceptron (MLP)**
This laboratory assignment focuses on the practical implementation of feedforward neural
networks for binary classification using structured/tabular data. Students will build, train, and
evaluate a Multi-Layer Perceptron (MLP) to predict credit risk, reinforcing core Unit 1
concepts such as neurons, activation functions, loss functions, and optimization.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load dataset
data = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/GermanCredit.csv")

# Handle missing values
data.fillna(method="ffill", inplace=True)

# Encode categorical features
for col in data.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])

# Features and target
X = data.drop("credit_risk", axis=1)
y = data["credit_risk"]

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42
)

# Build MLP
model = Sequential()

model.add(Dense(32, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train model
history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2
)

# Create directory for plots if it doesn't exist
if not os.path.exists('plots'):
    os.makedirs('plots')

# Plot accuracy
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("Accuracy Curve")
plt.legend(["Train", "Validation"])
plt.savefig("plots/accuracy_curve.png")
plt.show()

# Plot loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("Loss Curve")
plt.legend(["Train", "Validation"])
plt.savefig("plots/loss_curve.png")
plt.show()

# Predictions
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True)
plt.title("Confusion Matrix")
plt.savefig("plots/confusion_matrix.png")
plt.show()

print(classification_report(y_test, y_pred))